name: cureconnect
description: Smart Medicine Dispenser App for CureConnect project.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # مكتبات الربط بالسحاب (Firebase)
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  # أيقونات إضافية
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true
  
  # تعريف مكان اللوجو في المشروع
  assets:
    - assets/images/logo.png
