name: Flutter Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          
      - name: Add Google Services JSON
        run: |
          mkdir -p mobile_app/android/app
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > mobile_app/android/app/google-services.json

      - name: Create local.properties
        run: |
          echo "flutter.sdk=$FLUTTER_ROOT" > mobile_app/android/local.properties
      
      # خطوة مهمة لإعطاء صلاحيات البناء للسيرفر
      - name: Give Permissions
        run: chmod +x mobile_app/android/gradlew || true

      - name: Install dependencies
        run: |
          cd mobile_app
          flutter pub get
          
      - name: Build APK
        run: |
          cd mobile_app
          # أضفنا -v عشان يطبع لنا تفاصيل الخطأ لو فشل
          flutter build apk --release --no-tree-shake-icons -v
          
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: mobile_app/build/app/outputs/flutter-apk/app-release.apk
